## This workflow runs on all pull requests and issues.
## It greets new contributors when they create their first issue or open their first pull request.
##
## More details on https://github.com/actions/first-interaction

name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          issue-message: |
            # Issue Message with Markdown
            This is the message that will be displayed!
          pr-message: |
            # PR Message with Markdown
            This is the message that will be displayed!
          repo-token: ${{ secrets.GITHUB_TOKEN }}